### ISSUE TITLE
Request: Alert during business hours only

### ISSUE THREAD

**Issue by AnthonyIacono** [ClockStorm/clockstorm#11]
**Is your feature request related to a problem? Please describe.**
It would be nice if you could configure notifications to not occur outside of business hours.

**Describe the solution you'd like**
I'm not sure what I'd like more:
- Alerts automatically only from 9-5 _or_ a way to set your "notification hours" in options

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by amcarthur** [comment]
Should the business hours be configurable? My timezone is PST, but my "business hours" are adjusted for an EST based company.

**Comment by amcarthur** [comment]
Other users might have completely unconventional hours. Probably should be a separate issue, but I think the same thing could be said about making the end of week, and business week days in general, configurable.

**Comment by APIWT** [comment]
I think what we can do is just make it so you can configure it, but the default is 9-5 in your own timezone.
