### ISSUE TITLE
Allow me to set the time relative to Friday 10am before alarm triggers

### ISSUE THREAD

**Issue by neogeek13** [ClockStorm/clockstorm#18]
**Is your feature request related to a problem? Please describe.**
It's Thursday 10am. I have my expected timesheet Saved but I'm waiting on the PM for confirmation. I have a silent sound set but it's spinning. Which means I'm going to get used to ignoring the spinning. Which defeats the purpose of the thing in general. From week to week, I may need to vary when I have the knowledge I need to determine what's in my timesheet for the week.

**Describe the solution you'd like**
Allow me to set:
- Pause alarm until X hours prior to Timesheet due (Friday 10am EST)
- Bonus - add days + hours (say I want my alarms on Wed at 5pm - make that easy)

**Describe alternatives you've considered**
Use a Google calendar reminder and disable this tool until I'm on a stable project with normal reliable time categories

**Comment by APIWT** [comment]
Hello!

We are currently working on a PR which might be useful for this: https://github.com/ClockStorm/clockstorm/pull/17

This is kind of what the setting ends up looking like:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/45397889/230490523-b099187a-267a-4bb7-8e42-5b9555af8c8c.png">

Let me know if you think this would solve your problem. If not, I can take a deeper look :)
