### ISSUE TITLE
Request: link to settings within the expansion panel

### ISSUE THREAD

**Issue by willshowell** [ClockStorm/clockstorm#8]
It'd be nice to have a link to the extension settings here, so that you don't have to dig through the chrome extension manager

<img width="481" alt="image" src="https://user-images.githubusercontent.com/6475576/228316792-30783886-7ce6-417e-8d11-7d72d8ac15eb.png">

**Comment by AnthonyIacono** [comment]
Great idea!

**Comment by AnthonyIacono** [comment]
Here is what it looks like in main now:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/499404/228416556-375c5b53-6de9-45a1-84ac-e65bd82b7b4b.png">
